baseURL = 'https://Underday.github.io/'
languageCode = 'tr-tr'
title = 'Darma'
theme = 'PaperMod'
# 1. Arama iÃ§in gerekli veriyi (index.json) oluÅŸturur
[outputs]
  home = ["HTML", "RSS", "JSON"]

# 2. Butonu tepeye (menÃ¼ye) ekler
[[menu.main]]
  name = "Arama"
  url = "/search/"
  weight = 10
[params]
  defaultTheme = "auto" 
  ShowReadingTime = true 
  ShowShareButtons = true 

[params.homeInfoParams]
  Title = "Selam, ben Abdullah Talha ğŸ‘‹"
  Content = "Burada ÅŸiir ve denemeler bulacaksÄ±nÄ±z, iyi eÄŸlenceler"

# Sosyal Medya Ä°konlarÄ± (Her ikon iÃ§in [[...]] kullanÄ±lÄ±r)
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/Underday"

[[params.socialIcons]]
  name = "instagram"
  url = "https://instagram.com/atalhakorkmaz"
